#module FrobSplittingInfra
#
#using Oscar
#using Memoize
#using Combinatorics
#
#
#include("griffiths-dwork-construction/Utils.jl")
#
#export polynomial_frobenius_splitting
#export polynomial_frobenius_generator
#export multiply_then_split
#export is_kernel_poly_frob_generator
#export multicomibnations
#export Δ₁, Δ₁l, Fstar_basis
#export dim_of_homog_polys
#export vector, matrix_of_lin_op
#export lift_to_Int64
#export index_of_term_not_in_frobenius_power_CY
#export inPowerOfVariableIdeal
#export isHomog, isFSplit
#export matrix_of_multiply_then_split
#export matrix_of_multiply_then_split_sortmodp



exponent_vectors(poly) = leading_exponent_vector.(terms(poly))

"""
Evaluates the element of the Frobenius dual corresponding
to 'indices' for a polynomial ring (this happens to also be a splitting)
on the polynomial poly.

An element of the Frobenius dual is an element of 
Hom(F_*R, R), i.e. a map F_*R \\to R. 
Here, R = k[x_1, ..., x_n] is a polynomial ring, where
k is a field of characteristic p.

Such maps are in 1-1 correspondence with n-tuples
of integers mod p, where we have the maps
\\phi_{indices[1], ..., indices[n]},
as defined in the literature (see e.g. Ma-Polstra's notes).

Now, these maps are defined by projecting to the direct sum component,
which means we forget all but the terms which have exponent < indices[i] mod p
for the variable x_i, then we subtract the exponent of x_i by indices[i] and divide them all by p.

An example will be illustrive. Consider the element of the three-variable polynomial
ring k[x,y,z]: 

f = x^2y^3z + x^3y^2z^2 + x^8y^7z^7

and say that p = 5, then 

\\phi_{2,3,1}(f) = 1, and
\\phi_{3,2,2}(f) = 1 + xyz

Note: idk exactly what this is doing when you pass an element of a non-polynomial ring
... it probably throws an error on account of the use of 'gens'

Assumptions:

length(indices) == number of variables in the ring

indices \\in [0, ..., p-1]

"""
function polynomial_frobenius_splitting(p,poly,indices)

  #coefs = collect(coefficients(poly)) # someday use iterator to make this more efficient?
  #exp_vecs = exponent_vectors(poly)
  vars = gens(parent(poly))

  poly == zero(poly) && return 0
  length(vars) != length(indices) && begin println("mismatched number of variables"); return end

  result = zero(poly)
  for i in 1:length(poly)
    t = term(poly, i)
    exp_vec = exponent_vector(t,1)

    if all((exp_vec .% p) .== indices)


      new_exp_vec = divexact.(exp_vec .- indices,p) # the difision should be exact by the if statement
      
      c = coeff(t,1)
      new_term = c * prod(vars .^ new_exp_vec) 
      # uses that gens and leading_exponent_vector are using the same variable order

      result = result + new_term
    end
  end

  result

end#function

"""
By a standard argument, e.g. see Ma-Polstra,
Hom(F_*R, R) is generated by a single element,
which may be denoted 
\\phi_{p-1, ..., p-1} 
in the previous notation.
In Kawakami-Takamatsu-Yoshikawa, they denote this by u.

This function evaluates this generator at poly.
"""
function polynomial_frobenius_generator(p,poly) 
  nVars = length(gens(parent(poly)))

  polynomial_frobenius_splitting(p,poly,fill(p-1, nVars))
end#function

"""
Returns true if the polynomial inputted is in the
kernel of the map u that gnerates the dual module
of F_*
"""
function in_kernel_poly_frob_generator(p,poly)
  nVars = length(gens(parent(poly)))
  indices = fill(p-1,nVars)

  for i in 1:length(poly)

    t = term(poly, i)
    exp_vec = exponent_vector(t,1)

    if all((exp_vec .% p) .== indices)

      # this term will not be zero!
      return false
    end
  end

  return true
end#function

"""
    get_common_variable_factors(f)

Returns the monomial with largest exponents that
divides f
"""
function get_common_variable_factors(f)
    facts = collect(Oscar.factor(f))

    res_term = one(parent(f))
    for b in facts
        t = b[1]
        if length(terms(t)) == 1
            res_term *= t^b[2]
        end
    end

    exponent_vector(res_term,1) 
end



# MARK - computing Δ_1

"""
This is not as space-efficient as it could be

Gives the ways of putting the numbers 1...sum(partition)
into length(unique(partition)) boxes where each box
is labeled by a part value and box labeled
by partition[i] has 
count(==(partition[i]),partition) elements

list is assumed to be a list of indices, i.e.
a list of integers with no repeated elements.

partition is assumed to be a list of positive
integers whose which is in increasing or decreasing
order 
(though I think one can get away with each value
being in a contiguous interval of indices, i.e.
[1;1;1;2;2;3] is ok but [1;1;2;1] is not)

The resulting output is an array which has the same
length as partition, whose i'th element is in the
bucket labeled by partition[i]
"""
@memoize function multicombinations(list,partition)
  #TODO: can this be more space-efficient as an iterator??
  # TODO: rewrite this function to allocate memory smarter

  if length(partition) == 0
    return [zeros(eltype(partition),0)]
  end
  
  first = partition[1]
  nFirst = count(==(first),partition)

  result = Vector{Vector{eltype(list)}}()
  for combo in Combinatorics.combinations(list,nFirst)
    withoutfirst = partition[partition .!= first]
    withoutcombo = list[list .∉ (combo,)] # ∉ is \notin 

    for multicombo in multicombinations(withoutcombo,withoutfirst)
      push!(result,[combo; multicombo])
    end
  end

  result
end#function

"""
finds the multicombinations of the set {1, ... n},
where n is the sum of the elements in partition
"""
function multicombinations(partition)
  multicombinations(collect(1:sum(partition)),partition)
end#function

"""
Computes Δ₁(poly) by iterating
through all possible multicombinations 
(cross terms).
"""
function Δ₁(p,poly)
  
  # I don't know how computationally intense these operations are
  #    do them outside any loops just in case.
  terms_iter = terms(poly)
  allterms = collect(terms_iter)
  nTerms = length(allterms)

  res = zero(poly)

  for partition in Combinatorics.partitions(p)
    # the algorithm will still work without this line 
    # because div(1,p) == 0 so coef == 0 below...
    #
    # ...but let's not do the extra work.
    length(partition) == 1 && continue

    distParts = unique(partition)
    nDistParts = length(distParts)
  
    # println("Partition", partition)

    for termlist in Combinatorics.combinations(allterms,length(partition))
      
      coef = div(multinomial(partition...),p)

      # println("Coef: ", coef)

      for multicombo in multicombinations(collect(1:length(partition)),partition)

        # println("Multicombo: ", multicombo)

        newterm = one(poly)
        for i in 1:length(partition)
          exponent = partition[i]
          termind = multicombo[i]
          newterm = newterm * (termlist[termind])^exponent
        end

        # println("Term added: ", newterm)
        res = res + coef * newterm
      end

    end

  end

  res
end#function


"""
Returns Δ₁(poly), computed by
lifting to characteristic zero,
computing the cross terms, and
reducing again
"""
function Δ₁l(p,poly)

  R = parent(poly)

  originallift = map_coefficients(x -> lift(ZZ,x),poly)

  #println("Original Lift: ", originallift)

  ZR = parent(originallift)

  nocrossterms = sum(terms(originallift) .^p)
  withcrossterms = originallift^p

  #println("No cross terms: ", nocrossterms)
  #println("With cross terms: ", withcrossterms)

  crossterms = withcrossterms - nocrossterms

  #println("Just cross terms: ", crossterms)
  #(x,y,z,w) = gens(ZR)
  #println("Interesting coefficient: $(coeff(withcrossterms,x^14*y^27*z^11*w^28))")

  Δlift = map_coefficients(x -> divexact(x,p),crossterms)

  change_coefficient_ring(coefficient_ring(R),Δlift,parent=R)

end#function

function Δ₁l(poly::FqMPolyRingElem)
    p = poly.parent.data.n
    R = parent(poly)

    originallift = map_coefficients(x -> lift(ZZ, x),poly)

    nocrossterms = sum(terms(originallift) .^ p)
    withcrossterms = originallift ^ p
    crossterms = withcrossterms - nocrossterms
    Δlift = map_coefficients(x -> divexact(x, p),crossterms)
  
    change_coefficient_ring(coefficient_ring(R), Δlift, parent=R)
end

"""
Returns Δ₁(poly), computed by
lifting ℤ/p²ℤ.
"""
function Δ₁lp²(poly::FqMPolyRingElem)
    p = poly.parent.data.n
    R = parent(poly)
    n = poly.parent.data.nvars

    zzpoly = map_coefficients(x -> lift(ZZ, x), poly)
    ZZmp², _ = residue_ring(ZZ, p ^ 2)
    ZZmp²PolyRing, _ = polynomial_ring(ZZmp², n)

    originallift = change_base_ring(ZZmp², zzpoly; parent = ZZmp²PolyRing)

    nocrossterms = sum(terms(originallift) .^ p)
    withcrossterms = originallift ^ p
    crossterms = withcrossterms - nocrossterms

    Δlift = map_coefficients(x -> divexact(x, p), crossterms)
    Δlift = map_coefficients(x -> lift(ZZ, x), Δlift)

    change_coefficient_ring(coefficient_ring(R), Δlift, parent=R)
end

nvars(x::CufpMPolyRingElem) = x.parent.nvars

"""
    struct Δ₁Plan <: GPUPolynomials.OperationPlan

Struct caching information for computing Δ₁(`g`) quickly using 
multi-modular ntt and chinese remainder theorem

Fields:
    - `numVars`: number of variables
    - `prime`: characteristic of field of `g`
    - `key`: 1 + `totalDegree`, used to injectively map multivariate polynomial to univariate
    - `fftLen`: fft size
    - `totalDegree`: resulting homogeneous degree of `g` ^ `prime`
    - `primeArray`: list of NTT primes, their product being upper bond of `g` ^ `prime`
    - `nttType`: Integer type of NTT, currently always going to be UInt64
    - `nttPowPlans`: cached data for each NTT prime for speeding up NTT
    - `crtPlan`: some cached numbers for speeding up CRT
    - `memoryefficient`: if true, uses (significantly) slower algorithm with less GPU memory
"""
struct Δ₁Plan <: GPUPolynomials.OperationPlan
    numVars::Int
    prime::Int
    key::Int
    fftLen::Int
    totalDegree::Int
    primeArray::Vector
    nttType::DataType
    nttPowPlans::Vector{GPUPolynomials.NTTPowPlan}
    crtPlan::CuMatrix
    memoryefficient::Bool
end

"""
    function plan_Δ₁(numVars, prime)::Δ₁Plan

Generates a Δ₁Plan correpsonding to the quasi-f-split height problem where 
numVars = degree
"""
function plan_Δ₁(numVars, prime)::Δ₁Plan
    memoryefficient = false
    if (numVars, prime) == (4, 2)
        primeArray = UInt64.([12289])
    elseif (numVars, prime) == (4, 3)
        primeArray = UInt64.([0x3ffffff960000001])
    elseif (numVars, prime) == (4, 5)
        primeArray = UInt64.([0x3ffffff960000001])
    elseif (numVars, prime) == (4, 7)
        primeArray = UInt64.([0x3ffffff960000001, 0x3ffffff760000001])
    elseif (numVars, prime) == (4, 11)
        primeArray = UInt64.([0x3ffffff960000001, 0x3ffffff760000001, 0x3fffffeec0000001,  0x3fffffee60000001])
        memoryefficient = true
    elseif (numVars, prime) == (4, 13)
        primeArray = UInt64.([0x3ffffff960000001, 0x3ffffff760000001, 0x3fffffeec0000001,  0x3fffffee60000001])
        memoryefficient = true
    else
        throw(ArgumentError("I haven't figured out bounds for this yet!"))
    end

    resultTotalDegree = numVars * (prime - 1) * prime
    key = resultTotalDegree + 1
    fftLen = Base._nextpow2(resultTotalDegree * key^(numVars - 2) + 1)
    
    nttPowPlans = GPUPolynomials.NTTPowPlan[]
    # @assert all(isprime.(primeArray)) # yeah idk
    for p in primeArray
        nttPowPlan = GPUPolynomials.NTTPowPlan(fftLen, prime, p; memoryefficient = memoryefficient)
        push!(nttPowPlans, nttPowPlan)
    end
    resultDataType = GPUPolynomials.get_uint_type(max(Base._nextpow2(Int(ceil(log2(prod(BigInt.(primeArray)))))), 64))
    crtPlan = GPUPolynomials.plan_crt(resultDataType.(primeArray))

    return Δ₁Plan(numVars, prime, key, fftLen, resultTotalDegree, primeArray, eltype(primeArray), nttPowPlans, crtPlan, memoryefficient)
end

"""
Returns Δ₁(poly), computed on the GPU by
lifting to ℤ
"""
function Δ₁l(g::CufpMPolyRingElem)
    if !(g.opPlan isa Δ₁Plan)
        g.opPlan = plan_Δ₁(nvars(g), g.parent.n)
    end

    if g.opPlan.memoryefficient
        memoryefficient_Δ₁(g)
    else
        fast_Δ₁(g)
    end
end

"""
    function fast_Δ₁(g::CufpMPolyRingElem)

Computes g ^ p with multi-modular NTT and CRT, all on the GPU
"""
function fast_Δ₁(g::CufpMPolyRingElem)
    numVars = nvars(g)

    vecs = GPUPolynomials.get_dense_representation(g, g.opPlan.fftLen, g.bits, g.opPlan.nttType, g.opPlan.key, length(g.opPlan.nttPowPlans))

    currPtr = pointer(vecs)
    for planNum in eachindex(g.opPlan.nttPowPlans)
        vect = CUDA.unsafe_wrap(CuVector{g.opPlan.nttType}, currPtr, g.opPlan.fftLen)
        GPUPolynomials.ntt_pow!(vect, g.opPlan.nttPowPlans[planNum])
        currPtr += sizeof(g.opPlan.nttType) * g.opPlan.fftLen
    end

    remove_pth_power_terms(g, g.opPlan.key, vecs, g.opPlan.prime, g.opPlan.primeArray)

    multimodResultCoeffs, encodedDegs = GPUPolynomials.sparsify(vecs)
    CUDA.unsafe_free!(vecs)

    resultCoeffs = GPUPolynomials.build_result(multimodResultCoeffs, g.opPlan.crtPlan)
    CUDA.unsafe_free!(multimodResultCoeffs)

    divide_and_mod!(resultCoeffs, g.opPlan.prime)
    resultCoeffs = UInt64.(resultCoeffs)

    resultDegs = GPUPolynomials.kronecker_to_bitpacked(encodedDegs, g.opPlan.key, numVars, g.opPlan.totalDegree, g.bits, UInt)
    CUDA.unsafe_free!(encodedDegs)

    return CufpMPolyRingElem(resultCoeffs, resultDegs, g.bits, true, g.opPlan.totalDegree, g.parent, GPUPolynomials.EmptyPlan())
end

"""
    function fast_Δ₁(g::CufpMPolyRingElem)

Computes g ^ p with multi-modular NTT and CPU CRT.
"""
function memoryefficient_Δ₁(g::CufpMPolyRingElem)
    numVars = nvars(g)

    vecs = GPUPolynomials.cpu_get_dense_representation(g, g.opPlan.fftLen, g.bits, g.opPlan.nttType, g.opPlan.key, length(g.opPlan.nttPowPlans))

    currPtr = pointer(vecs)
    gpualloc = CUDA.zeros(g.opPlan.nttType, g.opPlan.fftLen)
    for planNum in eachindex(g.opPlan.nttPowPlans)
        cpuvec = unsafe_wrap(Vector{g.opPlan.nttType}, currPtr, g.opPlan.fftLen)
        copyto!(gpualloc, cpuvec)
        GPUPolynomials.ntt_pow!(gpualloc, g.opPlan.nttPowPlans[planNum])
        copyto!(cpuvec, gpualloc)
        currPtr += sizeof(g.opPlan.nttType) * g.opPlan.fftLen
    end
    
    remove_pth_power_terms(g, g.opPlan.key, vecs, g.opPlan.prime, g.opPlan.primeArray)

    multimodResultCoeffs, encodedDegs = GPUPolynomials.sparsify(vecs)
    multimodResultCoeffs = CuArray(multimodResultCoeffs)
    encodedDegs = CuArray(encodedDegs)

    resultCoeffs = GPUPolynomials.build_result(multimodResultCoeffs, g.opPlan.crtPlan)
    
    p = eltype(resultCoeffs)(g.opPlan.prime)
    cpu_resultCoeffs = Array(resultCoeffs)

    cpu_resultCoeffs .÷= p
    cpu_resultCoeffs .%= p
    cpu_resultCoeffs = UInt64.(cpu_resultCoeffs)
    resultCoeffs = CuArray(cpu_resultCoeffs)

    resultDegs = GPUPolynomials.kronecker_to_bitpacked(encodedDegs, g.opPlan.key, numVars, g.opPlan.totalDegree, g.bits, UInt)

    return CufpMPolyRingElem(resultCoeffs, resultDegs, g.bits, true, g.opPlan.totalDegree, g.parent, GPUPolynomials.EmptyPlan())
end

"""
    struct Δ₁Plan <: GPUPolynomials.OperationPlan

Struct caching information for computing Δ₁(`g`) quickly using 
multi-modular ntt and chinese remainder theorem

Fields:
    - `numVars`: number of variables
    - `prime`: characteristic of field of `g`
    - `smallKey` and `key`: used to injectively map multivariate polynomial to univariate
    - `smallFftLen` and `fftLen`: fft size
    - `smallForwardNTTPlan`, `smallInverseNTTPlan`, `forwardNTTPlan`, `inverseNTTPlan`: Cached data for performing NTTs
    - `totalDegree`: resulting homogeneous degree of `g` ^ `prime`
    - `fftPrime`: prime satisfying p = 2*fftlen + 1, hard coded to 0x3fffc00000000001
    - `itrs`: determines how many multiplication steps to take. `prime` = `power1` * `itrs` + `power2` is always true
"""
struct Δ₁lp²Plan <: GPUPolynomials.OperationPlan
    numVars::Int
    prime::Int
    smallKey::Int
    smallFftLen::Int
    smallForwardNTTPlan::NTTPlan
    smallInverseNTTPlan::INTTPlan
    key::Int
    fftLen::Int
    totalDegree::Int
    forwardNTTPlan::NTTPlan
    inverseNTTPlan::INTTPlan
    fftPrime::UInt64
    itrs::Int
    power1::Int
    power2::Int
end

"""
    function plan_Δ₁lp²(numVars, prime)::Δ₁lp²Plan

Generates a Δ₁Plan correpsonding to the quasi-f-split height problem where 
numVars = degree
"""
function plan_Δ₁lp²(numVars, prime)::Δ₁lp²Plan
    fftprime = 0x3fffc00000000001
    if (numVars, prime) == (4, 2)
        itrs = 0
        power1, power2 = 0, 2
    elseif (numVars, prime) == (4, 3)
        itrs = 0
        power1, power2 = 0, 3
    elseif (numVars, prime) == (4, 5)
        itrs = 0
        power1, power2 = 0, 5
    elseif (numVars, prime) == (4, 7)
        itrs = 1
        power1, power2 = 4, 3
    elseif (numVars, prime) == (4, 11)
        itrs = 2
        power1, power2 = 4, 3
    elseif (numVars, prime) == (4, 13)
        itrs = 3
        power1, power2 = 4, 1
    else
        throw(ArgumentError("I haven't figured out bounds for this yet!"))
    end

    smallTotalDegree = numVars * (prime - 1) * max(power1, power2)
    smallKey = smallTotalDegree + 1
    smallFftLen = Base._nextpow2(smallTotalDegree * smallKey ^ (numVars - 2) + 1)
    smallForwardPlan, smallInversePlan = plan_ntt(smallFftLen, fftprime, primitive_nth_root_of_unity(smallFftLen, fftprime))

    if itrs > 0
        resultTotalDegree = numVars * (prime - 1) * prime
        key = resultTotalDegree + 1
        fftLen = Base._nextpow2(resultTotalDegree * key ^ (numVars - 2) + 1)
        forwardPlan, inversePlan = plan_ntt(fftLen, fftprime, primitive_nth_root_of_unity(fftLen, fftprime))
    else
        resultTotalDegree = smallTotalDegree
        key = smallKey
        fftLen = smallFftLen
        forwardPlan, inversePlan = smallForwardPlan, smallInversePlan
    end

    return Δ₁lp²Plan(numVars, prime, smallKey, smallFftLen, smallForwardPlan, smallInversePlan, key, fftLen, resultTotalDegree, forwardPlan, inversePlan, fftprime, itrs, power1, power2)
end

function Δ₁lp²(g::CufpMPolyRingElem)
    if !(g.opPlan isa Δ₁lp²Plan)
        g.opPlan = plan_Δ₁lp²(nvars(g), g.parent.n)
    end

    if g.opPlan.itrs == 0
        return small_Δ₁lp²(g)
    else
        return large_Δ₁lp²(g)
    end
end

function small_Δ₁lp²(g::CufpMPolyRingElem)
    plan = g.opPlan
    p = UInt64(plan.prime)
    m = plan.forwardNTTPlan.reducer

    # convert g to dense fft form
    v = vec(GPUPolynomials.get_dense_representation(g, plan.smallFftLen, g.bits, UInt64, plan.smallKey, 1))

    # compute g^p
    ntt!(v, v, plan.smallForwardNTTPlan, true)
    GPUPolynomials.broadcast_pow!(v, plan.power2, m)
    intt!(v, v, plan.smallInverseNTTPlan, true)
    v .%= p ^ 2

    # subtract cross terms
    remove_pth_power_terms(g, plan.key, v, plan.prime, [p ^ 2])

    # make data sparse to eliminate unnecessary computations
    resultCoeffs, encodedDegs = GPUPolynomials.sparsify(v)
    CUDA.unsafe_free!(v)
    resultCoeffs = vec(resultCoeffs)

    divide_and_mod!(resultCoeffs, plan.prime)

    # change encoding of degrees to bitpacked form
    resultDegs = GPUPolynomials.kronecker_to_bitpacked(encodedDegs, plan.key, plan.numVars, plan.totalDegree, g.bits, UInt64)

    CUDA.unsafe_free!(encodedDegs)

    return CufpMPolyRingElem(resultCoeffs, resultDegs, g.bits, true, plan.totalDegree, g.parent, GPUPolynomials.EmptyPlan())
end

function large_Δ₁lp²(g::CufpMPolyRingElem)
    plan = g.opPlan
    p = UInt64(plan.prime)
    m = plan.forwardNTTPlan.reducer
    itrs = plan.itrs

    # convert g to dense fft form
    smallv = vec(GPUPolynomials.get_dense_representation(g, plan.smallFftLen, g.bits, UInt64, plan.smallKey, 1))

    ntt!(smallv, smallv, plan.smallForwardNTTPlan, true)

    smallaux = copy(smallv)
    GPUPolynomials.broadcast_pow!(smallaux, plan.power1, m)
    intt!(smallaux, smallaux, plan.smallInverseNTTPlan, true)
    smallaux .%= p ^ 2 # smallaux holds g^pow1
    
    aux = CUDA.zeros(UInt64, plan.fftLen)
    change_encoding(smallaux, aux, plan.smallKey, plan.key, plan.numVars) # aux holds g^pow1
    CUDA.unsafe_free!(smallaux)
    ntt!(aux, aux, plan.forwardNTTPlan, true)

    GPUPolynomials.broadcast_pow!(smallv, plan.power2, m)
    intt!(smallv, smallv, plan.smallInverseNTTPlan, true)
    smallv .%= p ^ 2 # smallv holds g^pow2

    v = CUDA.zeros(UInt64, plan.fftLen)
    change_encoding(smallv, v, plan.smallKey, plan.key, plan.numVars) # v holds g^pow2
    CUDA.unsafe_free!(smallv)
    
    for i in 1:itrs
        ntt!(v, v, plan.forwardNTTPlan, true)
        broadcast_mul!(v, aux, plan.forwardNTTPlan.reducer) # v = v * aux
        intt!(v, v, plan.inverseNTTPlan, true)
        v .%= p ^ 2
    end

    CUDA.unsafe_free!(aux)

    remove_pth_power_terms(g, plan.key, v, plan.prime, [p ^ 2])

    resultCoeffs, encodedDegs = GPUPolynomials.sparsify(v)
    resultCoeffs = vec(resultCoeffs)
    CUDA.unsafe_free!(v)
    
    divide_and_mod!(resultCoeffs, plan.prime)

    resultDegs = GPUPolynomials.kronecker_to_bitpacked(encodedDegs, plan.key, plan.numVars, plan.totalDegree, g.bits, UInt64)
    CUDA.unsafe_free!(encodedDegs)

    return CufpMPolyRingElem(resultCoeffs, resultDegs, g.bits, true, plan.totalDegree, g.parent, GPUPolynomials.EmptyPlan())
end


"""
If R is the polynomial ring in N variables,
returns a basis for R as an R^p - module,
equivalently returns a basis for
F_*R as an R-module.

"""
function Fstar_basis(p,poly)
  vars = gens(parent(poly))
  n = length(vars)

  numgens = p^n - 1

  generators = zeros(parent(poly),fill(Int(p),n)...)
  for i in CartesianIndices(generators)
    exps = Tuple(i) .- 1
    generators[i] = prod(vars .^ exps)
  end

  vec(generators)
end#function

dim_of_homog_polys(n,d)  = binomial(n+d-1,n-1) # n+d-1 choose n-1

"""
Gives the index of the "critical term", i.e. the one
that determines whether or not something is quasi-F-split
for a CY manifold. This term is the degree (p-1)^n
monomial x_1^(p-1) ... x_n^(p-1)

"""
function index_of_term_not_in_frobenius_power_CY(p,n,order=:lex)
  R, vars = polynomial_ring(GF(p),n)
  
  crit_term = prod(vars .^ (p-1))

  # perhaps assert this has only one element?
  findfirst(vector(crit_term,total_degree(crit_term)) .!= 0)
end

"""
Returns true if the polynomial f 
is in the "frobenius power" \\frak{m}^[m],
where \\frak{m} is the ideal of variables of the ring.

"""
function inPowerOfVariableIdeal(p,m,f)
  # don't need this because exponent_vectors will have 
  # no elements for the zero polynomial
  f == zero(f) && return true


  for i in 1:length(f)
    ev = exponent_vector(f,i)

    if all(ev .< m)
      #println("Found term not in the Frob power of the maximal ideal: " * string(exponent_vector))
      
      # We not in the power of the maximal ideal, we don't have any
      # powers that are big enough
      return false
    end
  end

  true
end#function

"""
Returns true if the polyonoimal is homogenous.

doesn't seem to be fully implemented in Oscar :(

try 'is_homogeneous', doesn't seem to be implemented 
for fpMPolyRingElem
"""
function isHomog(poly;ofdegree=-1)

  evs = exponent_vectors(poly)

  if ofdegree == -1 
    all(sum.(evs) .== sum(evs[1]))
  else
    all(sum.(evs) .== ofdegree)
  end
end#function

function bracketpower(I,m)
    R = base_ring(I)

    res = zeros(R,0)
    for g in gens(I)
        new_gen = g^m
        push!(res,new_gen)
    end

    ideal(R,res)
end


function fedderColonIdeal(I)
    p = characteristic(base_ring(I))
    bracketpower(I,p):I
end


# MARK - calculations of quasi-F-split height in one form or another

"""
Calculates if the hypersuface defined by the 
polynomial poly is F-split

note that p must be prime for this to have mathematical meaning
"""
function isFSplit(p,poly)
  #maybe TODO: check that p is prime

  !inPowerOfVariableIdeal(p,p,poly^(p-1))

end#function

function isFSplit(I)
    p = characteristic(base_ring(I))
    J = fedderColonIdeal(I)
    !all(inPowerOfVariableIdeal.(p,p,gens(J)))
end


"""

Examples

```
julia> p = 3

julia> R, (x,y,z,w,u,v) = polynomial_ring(ZZ,6)

julia> g1 = x^2*y^2*z^2*w^2*v^2*u^2*p + 2x^12 + y^6*x^6

julia> in1FInjectiveIdeal(g1,3)
false

julia> g2 = x^2*y^2*z^2*w^2*v^2*u^2*p^2 + 2x^12 + y^6*x^6

julia> in1FInjectiveIdeal(g2,3)
true

julia> g3 = x^2*y^3*z^2*w^2*v*u^2*2 + 2x^12 + z^6*w^6 + w^4*v^4*z^4

julia> in1FInjectiveIdeal(g3,3)
false

julia> g4 = x^2*y^3*z^2*w^2*v*u^2*3 + 2x^12 + z^6*w^6 + w^4*v^4*z^4

julia> in1FInjectiveIdeal(g4,3)
true
```
"""
function in1FInjectiveIdeal(g,p)
    # don't need this because exponent_vectors will have 
    # no elements for the zero polynomial
    g == zero(g) && return true

#     p = characteristic(parent(g))

    f = g#^(2p-2)

    for i in 1:length(f)
        ev = exponent_vector(f,i)
        c = coeff(f,i)

        ev_lt_p = ev .< p
        # println(ev)
        # println(c)
        #println(all(ev .< 2p))
        #println(count(==(false), ev_lt_p) == 1)
        #println(c % p != 0)

        if all(ev_lt_p) && (c % p^2 != 0)
            # println("found type 1")
          
            # We not in the power of the maximal ideal, we don't have any
            # powers that are big enough
            return false
        elseif all(ev .< 2p) && 
               count(==(false), ev_lt_p) == 1 &&
               c % p != 0
            # println("found type 2")

            return false
        end
    end

    true
end

function is1FInjective(f,p)
    g = f^(2p-2)
    !in1FInjectiveIdeal(g,p)
end
